### ISSUE TITLE
Create showcase page

### ISSUE THREAD

**Issue by spoenemann** [langium/langium-website#49]
We want to create a subpage langium.org/showcase in the same style and technology (HTML + Tailwind) as the main page. Eventually this will list DSL examples that will be available each in a subpage. Let's start with the `statemachine` example. The examples could be listed with cards, similar to https://www.typefox.io/blog/ or so.

**Comment by montymxb** [comment]
Just to make some notes here. My plan is to finish some layout changes that Markus started last week later today. This will be cleaning up the layout for the home page & imprint pages, since there were some issues there while refactoring things to bring in the new showcase page. This is separate from Guillaume, who is focusing on the showcase page directly.

**Comment by spoenemann** [comment]
Fixed with #52
